apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsvpwa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dsvpwa
  template:
    metadata:
      labels:
        app: dsvpwa
    spec:
      containers:
        - name: dsvpwa
          image: ghcr.io/taher-alsaegh/dsvpwa:0.1.4@sha256:678456a0481420bef5b0c27066df1773698b3daabe9052e66aeae4d125cd26f5
          ports:
            - containerPort: 8080

